---

#
# This file is part of the `src-run/augustus-deprecation-library` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
#

sudo     : false
language : php
php      : [ 7.0, 7.1, nightly ]

git:
  depth : 3

env :
  global :
    - SYMFONY_DEPRECATIONS_HELPER: weak
    - secure : OtJIJkQuAT0gWjcNRorrSnyvxGmIpB3fkxYi2OL9eTTCcUCmIc5l6pnAlEkRfYgzrKUMc3BBv9AEppEdWm6nBoFER8MYvpSqhUoW/LhHKlxmNc733iXjBUe02+2VsaztgofvcDe56+YndL38cO00HLmKpQPLoepWAQ3f8+kBHrvb4LwEhsbmLDg31KMUzRyS1Fw6tfjKofHZfJSQQov1OCoNVnIPL7JwUWYqn133dKU+XZfa8acLN2TyX/rheQHz1YE7lQ+76rBisjz5N54oY3RcC/dnJ7VC3hHFR5nFWYre0eijmUr/5N5+gl7JW8UDRpKMo2+7H2dNEJ0tuAZCbtKoMcjvHLEkv/bE4hNd+1hXaL7WsL82yLz9+4ZlkRnIhh0/iT9PkEsDtZjsgA+7lw4i8nlndysb8zkqJwS0C47hg3ocmUIiohn25qMEfODOxSnkosjRGvsBwrBBV7QgSXN2IbDTJxGvgj+L29fala2z2Szrb/Ed+axGUZgGFxw8hdY33ozaTxK1FF6lcwXM+GwEji6JifgeroXQVUKtNjUOMhao5LS8XIaZFZfuhBGhLmmhsMoxQsU/TGExWb/yUQCR1+wj9Xf6yZcCbGV+Jxl6MmLpCcmpo4FqBkq7SvxVCvuSEs83bG0LqK+noJBNTYd5cuAywbHuQ6HEV+7llWU=

install :
  - bash .bldr/bldr -b up-env -q
  - bash .bldr/bldr -b up-app -q

script :
  - bin/simple-phpunit | bin/phpunit -vvv

after_script :
  - bash .bldr/bldr -b down-app -q
  - bash .bldr/bldr -b down-env -q

...
